# Databricks notebook source
"""
Databricks PySpark Batch Telemetry Parsing & Delta Lake Ingestion Job.

This job:
1. Ingests raw JSON Lines telemetry logs generated by the /v1/ingest API endpoint.
2. Uses PySpark Schema Evolution ('mergeSchema' = True) to dynamically adapt to nested metadata.
3. Cleans, normalizes, and partitions data into 'traces_silver' and 'spans_silver' Delta tables.
4. Aggregates performance, latency percentiles, and token metrics into 'evaluations_gold'.
"""

import sys
from datetime import datetime, timezone
try:
    from pyspark.sql import SparkSession
    from pyspark.sql import functions as F
    from pyspark.sql.types import (
        StructType,
        StructField,
        StringType,
        TimestampType,
        DoubleType,
        IntegerType,
        MapType,
    )
except ImportError:
    # PySpark is executed on Databricks clusters; local fallback mocks SparkSession for linting/unit check
    SparkSession = None
    F = None


def run_pipeline(
    spark,
    raw_logs_path: str,
    delta_silver_traces_path: str,
    delta_silver_spans_path: str,
    delta_gold_evals_path: str,
    target_date: str = None
):
    """
    Execute the telemetry parsing and Delta Lake compaction pipeline.
    """
    if target_date is None:
        target_date = datetime.now(timezone.utc).strftime("%Y/%m/%d")

    input_path = f"{raw_logs_path.rstrip('/')}/{target_date}/*.jsonl"
    print(f"[Telemetria ETL] Reading raw logs from: {input_path}")

    # 1. Ingest raw JSONL logs with permissive schema inference for dynamic metadata
    raw_df = spark.read.option("multiline", "false").json(input_path)

    # 2. Extract and parse Traces Silver
    # Filter for trace records or records having 'trace_id'
    traces_df = raw_df.filter(F.col("record_type") == "trace") if "record_type" in raw_df.columns else raw_df
    
    traces_silver = (
        traces_df.select(
            F.col("trace_id").cast(StringType()),
            F.col("project_id").cast(StringType()),
            F.coalesce(F.col("session_id"), F.lit("default")).alias("session_id"),
            F.col("input").cast(StringType()),
            F.col("output").cast(StringType()),
            F.col("expected_output").cast(StringType()),
            F.to_timestamp(F.col("start_time")).alias("start_time"),
            F.to_timestamp(F.col("end_time")).alias("end_time"),
            F.coalesce(F.col("latency_ms"), F.lit(0.0)).cast(DoubleType()).alias("latency_ms"),
            F.coalesce(F.col("tags"), F.create_map()).alias("tags"),
            F.to_json(F.col("metadata")).alias("metadata"),
            F.to_date(F.col("start_time")).alias("date_partition")
        )
    )

    # Write to traces_silver with schema evolution
    print(f"[Telemetria ETL] Writing to Traces Silver Delta table: {delta_silver_traces_path}")
    (
        traces_silver.write
        .format("delta")
        .mode("append")
        .option("mergeSchema", "true")
        .partitionBy("project_id", "date_partition")
        .save(delta_silver_traces_path)
    )

    # 3. Extract and parse Spans Silver
    # Raw logs may contain standalone span records or spans nested inside trace records
    if "spans" in raw_df.columns:
        nested_spans = traces_df.filter(F.size(F.col("spans")) > 0).select(
            F.explode(F.col("spans")).alias("span")
        ).select("span.*")
    else:
        nested_spans = None

    direct_spans = raw_df.filter(F.col("record_type") == "span") if "record_type" in raw_df.columns else None

    if nested_spans is not None and direct_spans is not None:
        combined_spans = nested_spans.unionByName(direct_spans, allowMissingColumns=True)
    elif nested_spans is not None:
        combined_spans = nested_spans
    elif direct_spans is not None:
        combined_spans = direct_spans
    else:
        combined_spans = spark.createDataFrame([], schema=StructType([]))

    if combined_spans.count() > 0 if hasattr(combined_spans, "count") else False:
        spans_silver = (
            combined_spans.select(
                F.col("span_id").cast(StringType()),
                F.col("trace_id").cast(StringType()),
                F.col("parent_span_id").cast(StringType()),
                F.coalesce(F.col("span_type"), F.lit("function")).cast(StringType()).alias("span_type"),
                F.col("model_name").cast(StringType()),
                F.coalesce(F.col("prompt_tokens"), F.lit(0)).cast(IntegerType()).alias("prompt_tokens"),
                F.coalesce(F.col("completion_tokens"), F.lit(0)).cast(IntegerType()).alias("completion_tokens"),
                F.col("raw_request").cast(StringType()),
                F.col("raw_response").cast(StringType()),
            )
        )

        print(f"[Telemetria ETL] Writing to Spans Silver Delta table: {delta_silver_spans_path}")
        (
            spans_silver.write
            .format("delta")
            .mode("append")
            .option("mergeSchema", "true")
            .partitionBy("span_type")
            .save(delta_silver_spans_path)
        )

    # 4. Generate Gold Aggregations (Evaluations, P95 Latency, Token Usage)
    print(f"[Telemetria ETL] Computing Gold Metric Aggregations: {delta_gold_evals_path}")
    gold_metrics = (
        traces_silver.groupBy("project_id", "date_partition")
        .agg(
            F.count("trace_id").alias("total_runs"),
            F.avg("latency_ms").alias("avg_latency_ms"),
            F.expr("percentile_approx(latency_ms, 0.95)").alias("p95_latency_ms"),
            F.sum(F.when(F.col("tags.status") == "error", 0).otherwise(1)).cast(DoubleType()) / F.count("trace_id").alias("success_rate"),
            F.current_timestamp().alias("computed_at")
        )
    )

    (
        gold_metrics.write
        .format("delta")
        .mode("append")
        .option("mergeSchema", "true")
        .partitionBy("project_id")
        .save(delta_gold_evals_path)
    )

    print("[Telemetria ETL] Successfully completed batch processing.")


if __name__ == "__main__":
    if SparkSession is not None:
        spark_session = (
            SparkSession.builder
            .appName("Telemetria-Batch-Log-Processor")
            .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
            .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
            .getOrCreate()
        )

        raw_path = sys.argv[1] if len(sys.argv) > 1 else "/mnt/telemetria/staging/raw_logs"
        silver_t_path = sys.argv[2] if len(sys.argv) > 2 else "/mnt/telemetria/delta/traces_silver"
        silver_s_path = sys.argv[3] if len(sys.argv) > 3 else "/mnt/telemetria/delta/spans_silver"
        gold_path = sys.argv[4] if len(sys.argv) > 4 else "/mnt/telemetria/delta/evaluations_gold"

        run_pipeline(
            spark=spark_session,
            raw_logs_path=raw_path,
            delta_silver_traces_path=silver_t_path,
            delta_silver_spans_path=silver_s_path,
            delta_gold_evals_path=gold_path
        )
    else:
        print("[Telemetria ETL] Local Python runtime verified (PySpark installed in cluster environment).")
