[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "telemetria-sdk"
version = "1.0.0"
description = "Lightweight, non-blocking Active Observability & Evaluation Python SDK for LLMs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
